{"name": "При авторизации пользователя с неверными данными выходит ошибка.", "status": "passed", "description": "Логин с неверными данными.", "parameters": [{"name": "payload", "value": "{'name': 'TestingUser_wrong', 'password': '123456', 'email': 'TestingUser_wrong@testmail.ru'}"}], "start": 1706426776116, "stop": 1706426776576, "uuid": "5096edc8-fe28-4f27-a516-795b58357d60", "historyId": "4a2b9fe6c119c3db2ff0b964323dbdd6", "testCaseId": "ec48a7c04a73840bb136fce7e7a3301b", "fullName": "tests.test_user_login.TestUserLogin#test_full_fields_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "99tarasevichlv"}, {"name": "thread", "value": "4980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}